namespace NightWatchman
{
    public enum EInteractableIds
    {
        Desk,
        Table,
        Table_1,
        CoatHook,
        Firewood,
        Chair,
        Chair_1,
        Chair_2,
        Chair_3,
        Barrel_1,
        Carpet_Red,
        Carpet_Red_1,
        Bench,
        Bucket,
        Candlier,
        Fireplace,
        Fireplace_1,
        Carpet_Green,
        Shelf,
        WeaponRack_Small,
        Chest,
        Chest_1,
        Big_Shelf,
        Big_Shelf_1,
        Big_Shelf_2,
        Banner,
        Table_Big,
        Throne,
        Throne_1,
        Firewood_1
    }
}